# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: redmine.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='redmine.proto',
  package='package.name',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rredmine.proto\x12\x0cpackage.name\"k\n\x0bissueObject\x12\x14\n\x0cproject_name\x18\x01 \x01(\t\x12\x13\n\x0bissue_title\x18\x02 \x01(\t\x12\x19\n\x11issue_description\x18\x03 \x01(\t\x12\x16\n\x0eissue_priority\x18\x04 \x01(\t\"a\n\x10serverCredential\x12\x18\n\x10redmine_username\x18\x01 \x01(\t\x12\x18\n\x10redmine_password\x18\x02 \x01(\t\x12\x19\n\x11redmine_server_ip\x18\x03 \x01(\t\"r\n\x12insertIssueRequest\x12\x32\n\ncredential\x18\x01 \x01(\x0b\x32\x1e.package.name.serverCredential\x12(\n\x05issue\x18\x02 \x01(\x0b\x32\x19.package.name.issueObject\"_\n\x08response\x12\x38\n\x10operation_result\x18\x01 \x01(\x0e\x32\x1e.package.name.operationResults\x12\x19\n\x11operation_message\x18\x02 \x01(\t*,\n\x10operationResults\x12\x0b\n\x07\x46\x41ILURE\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x32W\n\x07redmine\x12L\n\x0einsertIssueRPC\x12 .package.name.insertIssueRequest\x1a\x16.package.name.response\"\x00\x62\x06proto3'
)

_OPERATIONRESULTS = _descriptor.EnumDescriptor(
  name='operationResults',
  full_name='package.name.operationResults',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=452,
  serialized_end=496,
)
_sym_db.RegisterEnumDescriptor(_OPERATIONRESULTS)

operationResults = enum_type_wrapper.EnumTypeWrapper(_OPERATIONRESULTS)
FAILURE = 0
SUCCESS = 1



_ISSUEOBJECT = _descriptor.Descriptor(
  name='issueObject',
  full_name='package.name.issueObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='project_name', full_name='package.name.issueObject.project_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='issue_title', full_name='package.name.issueObject.issue_title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='issue_description', full_name='package.name.issueObject.issue_description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='issue_priority', full_name='package.name.issueObject.issue_priority', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=138,
)


_SERVERCREDENTIAL = _descriptor.Descriptor(
  name='serverCredential',
  full_name='package.name.serverCredential',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='redmine_username', full_name='package.name.serverCredential.redmine_username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='redmine_password', full_name='package.name.serverCredential.redmine_password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='redmine_server_ip', full_name='package.name.serverCredential.redmine_server_ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=237,
)


_INSERTISSUEREQUEST = _descriptor.Descriptor(
  name='insertIssueRequest',
  full_name='package.name.insertIssueRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='credential', full_name='package.name.insertIssueRequest.credential', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='issue', full_name='package.name.insertIssueRequest.issue', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=239,
  serialized_end=353,
)


_RESPONSE = _descriptor.Descriptor(
  name='response',
  full_name='package.name.response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation_result', full_name='package.name.response.operation_result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='operation_message', full_name='package.name.response.operation_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=450,
)

_INSERTISSUEREQUEST.fields_by_name['credential'].message_type = _SERVERCREDENTIAL
_INSERTISSUEREQUEST.fields_by_name['issue'].message_type = _ISSUEOBJECT
_RESPONSE.fields_by_name['operation_result'].enum_type = _OPERATIONRESULTS
DESCRIPTOR.message_types_by_name['issueObject'] = _ISSUEOBJECT
DESCRIPTOR.message_types_by_name['serverCredential'] = _SERVERCREDENTIAL
DESCRIPTOR.message_types_by_name['insertIssueRequest'] = _INSERTISSUEREQUEST
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['operationResults'] = _OPERATIONRESULTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

issueObject = _reflection.GeneratedProtocolMessageType('issueObject', (_message.Message,), {
  'DESCRIPTOR' : _ISSUEOBJECT,
  '__module__' : 'redmine_pb2'
  # @@protoc_insertion_point(class_scope:package.name.issueObject)
  })
_sym_db.RegisterMessage(issueObject)

serverCredential = _reflection.GeneratedProtocolMessageType('serverCredential', (_message.Message,), {
  'DESCRIPTOR' : _SERVERCREDENTIAL,
  '__module__' : 'redmine_pb2'
  # @@protoc_insertion_point(class_scope:package.name.serverCredential)
  })
_sym_db.RegisterMessage(serverCredential)

insertIssueRequest = _reflection.GeneratedProtocolMessageType('insertIssueRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTISSUEREQUEST,
  '__module__' : 'redmine_pb2'
  # @@protoc_insertion_point(class_scope:package.name.insertIssueRequest)
  })
_sym_db.RegisterMessage(insertIssueRequest)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'redmine_pb2'
  # @@protoc_insertion_point(class_scope:package.name.response)
  })
_sym_db.RegisterMessage(response)



_REDMINE = _descriptor.ServiceDescriptor(
  name='redmine',
  full_name='package.name.redmine',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=498,
  serialized_end=585,
  methods=[
  _descriptor.MethodDescriptor(
    name='insertIssueRPC',
    full_name='package.name.redmine.insertIssueRPC',
    index=0,
    containing_service=None,
    input_type=_INSERTISSUEREQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REDMINE)

DESCRIPTOR.services_by_name['redmine'] = _REDMINE

# @@protoc_insertion_point(module_scope)
